// Global city-to-IANA-timezone mappings for autocomplete
// Each entry: { city: "Display Name", tz: "IANA/Timezone_ID", country: "CC" }
window.__TZ_CITIES = [
  // Special entries
  { city: "UTC", tz: "UTC", country: "" },
  { city: "GMT", tz: "GMT", country: "" },

  // North America — United States
  { city: "New York", tz: "America/New_York", country: "US" },
  { city: "Los Angeles", tz: "America/Los_Angeles", country: "US" },
  { city: "Chicago", tz: "America/Chicago", country: "US" },
  { city: "Houston", tz: "America/Chicago", country: "US" },
  { city: "Phoenix", tz: "America/Phoenix", country: "US" },
  { city: "Philadelphia", tz: "America/New_York", country: "US" },
  { city: "San Antonio", tz: "America/Chicago", country: "US" },
  { city: "San Diego", tz: "America/Los_Angeles", country: "US" },
  { city: "Dallas", tz: "America/Chicago", country: "US" },
  { city: "San Francisco", tz: "America/Los_Angeles", country: "US" },
  { city: "Austin", tz: "America/Chicago", country: "US" },
  { city: "Seattle", tz: "America/Los_Angeles", country: "US" },
  { city: "Denver", tz: "America/Denver", country: "US" },
  { city: "Boston", tz: "America/New_York", country: "US" },
  { city: "Washington DC", tz: "America/New_York", country: "US" },
  { city: "Miami", tz: "America/New_York", country: "US" },
  { city: "Atlanta", tz: "America/New_York", country: "US" },
  { city: "Detroit", tz: "America/Detroit", country: "US" },
  { city: "Minneapolis", tz: "America/Chicago", country: "US" },
  { city: "Las Vegas", tz: "America/Los_Angeles", country: "US" },
  { city: "Portland", tz: "America/Los_Angeles", country: "US" },
  { city: "Anchorage", tz: "America/Anchorage", country: "US" },
  { city: "Honolulu", tz: "Pacific/Honolulu", country: "US" },
  { city: "Indianapolis", tz: "America/Indiana/Indianapolis", country: "US" },
  { city: "Nashville", tz: "America/Chicago", country: "US" },
  { city: "Charlotte", tz: "America/New_York", country: "US" },
  { city: "Salt Lake City", tz: "America/Denver", country: "US" },
  { city: "Pittsburgh", tz: "America/New_York", country: "US" },
  { city: "St Louis", tz: "America/Chicago", country: "US" },

  // North America — Canada
  { city: "Toronto", tz: "America/Toronto", country: "CA" },
  { city: "Vancouver", tz: "America/Vancouver", country: "CA" },
  { city: "Montreal", tz: "America/Toronto", country: "CA" },
  { city: "Calgary", tz: "America/Edmonton", country: "CA" },
  { city: "Edmonton", tz: "America/Edmonton", country: "CA" },
  { city: "Ottawa", tz: "America/Toronto", country: "CA" },
  { city: "Winnipeg", tz: "America/Winnipeg", country: "CA" },
  { city: "Halifax", tz: "America/Halifax", country: "CA" },
  { city: "St Johns", tz: "America/St_Johns", country: "CA" },
  { city: "Regina", tz: "America/Regina", country: "CA" },

  // North America — Mexico
  { city: "Mexico City", tz: "America/Mexico_City", country: "MX" },
  { city: "Guadalajara", tz: "America/Mexico_City", country: "MX" },
  { city: "Monterrey", tz: "America/Monterrey", country: "MX" },
  { city: "Cancun", tz: "America/Cancun", country: "MX" },
  { city: "Tijuana", tz: "America/Tijuana", country: "MX" },

  // Central America & Caribbean
  { city: "Guatemala City", tz: "America/Guatemala", country: "GT" },
  { city: "San Salvador", tz: "America/El_Salvador", country: "SV" },
  { city: "Tegucigalpa", tz: "America/Tegucigalpa", country: "HN" },
  { city: "Managua", tz: "America/Managua", country: "NI" },
  { city: "San Jose", tz: "America/Costa_Rica", country: "CR" },
  { city: "Panama City", tz: "America/Panama", country: "PA" },
  { city: "Havana", tz: "America/Havana", country: "CU" },
  { city: "Kingston", tz: "America/Jamaica", country: "JM" },
  { city: "Port-au-Prince", tz: "America/Port-au-Prince", country: "HT" },
  { city: "Santo Domingo", tz: "America/Santo_Domingo", country: "DO" },
  { city: "San Juan", tz: "America/Puerto_Rico", country: "PR" },
  { city: "Nassau", tz: "America/Nassau", country: "BS" },
  { city: "Belize City", tz: "America/Belize", country: "BZ" },

  // South America
  { city: "Sao Paulo", tz: "America/Sao_Paulo", country: "BR" },
  { city: "Rio de Janeiro", tz: "America/Sao_Paulo", country: "BR" },
  { city: "Brasilia", tz: "America/Sao_Paulo", country: "BR" },
  { city: "Manaus", tz: "America/Manaus", country: "BR" },
  { city: "Buenos Aires", tz: "America/Argentina/Buenos_Aires", country: "AR" },
  { city: "Santiago", tz: "America/Santiago", country: "CL" },
  { city: "Lima", tz: "America/Lima", country: "PE" },
  { city: "Bogota", tz: "America/Bogota", country: "CO" },
  { city: "Medellin", tz: "America/Bogota", country: "CO" },
  { city: "Caracas", tz: "America/Caracas", country: "VE" },
  { city: "Quito", tz: "America/Guayaquil", country: "EC" },
  { city: "Guayaquil", tz: "America/Guayaquil", country: "EC" },
  { city: "La Paz", tz: "America/La_Paz", country: "BO" },
  { city: "Montevideo", tz: "America/Montevideo", country: "UY" },
  { city: "Asuncion", tz: "America/Asuncion", country: "PY" },
  { city: "Georgetown", tz: "America/Guyana", country: "GY" },
  { city: "Paramaribo", tz: "America/Paramaribo", country: "SR" },
  { city: "Cayenne", tz: "America/Cayenne", country: "GF" },

  // Europe — Western
  { city: "London", tz: "Europe/London", country: "GB" },
  { city: "Manchester", tz: "Europe/London", country: "GB" },
  { city: "Edinburgh", tz: "Europe/London", country: "GB" },
  { city: "Dublin", tz: "Europe/Dublin", country: "IE" },
  { city: "Paris", tz: "Europe/Paris", country: "FR" },
  { city: "Lyon", tz: "Europe/Paris", country: "FR" },
  { city: "Marseille", tz: "Europe/Paris", country: "FR" },
  { city: "Amsterdam", tz: "Europe/Amsterdam", country: "NL" },
  { city: "Brussels", tz: "Europe/Brussels", country: "BE" },
  { city: "Luxembourg", tz: "Europe/Luxembourg", country: "LU" },

  // Europe — Central
  { city: "Berlin", tz: "Europe/Berlin", country: "DE" },
  { city: "Munich", tz: "Europe/Berlin", country: "DE" },
  { city: "Frankfurt", tz: "Europe/Berlin", country: "DE" },
  { city: "Hamburg", tz: "Europe/Berlin", country: "DE" },
  { city: "Vienna", tz: "Europe/Vienna", country: "AT" },
  { city: "Zurich", tz: "Europe/Zurich", country: "CH" },
  { city: "Geneva", tz: "Europe/Zurich", country: "CH" },
  { city: "Prague", tz: "Europe/Prague", country: "CZ" },
  { city: "Warsaw", tz: "Europe/Warsaw", country: "PL" },
  { city: "Krakow", tz: "Europe/Warsaw", country: "PL" },
  { city: "Budapest", tz: "Europe/Budapest", country: "HU" },
  { city: "Bratislava", tz: "Europe/Bratislava", country: "SK" },
  { city: "Ljubljana", tz: "Europe/Ljubljana", country: "SI" },

  // Europe — Southern
  { city: "Rome", tz: "Europe/Rome", country: "IT" },
  { city: "Milan", tz: "Europe/Rome", country: "IT" },
  { city: "Madrid", tz: "Europe/Madrid", country: "ES" },
  { city: "Barcelona", tz: "Europe/Madrid", country: "ES" },
  { city: "Lisbon", tz: "Europe/Lisbon", country: "PT" },
  { city: "Athens", tz: "Europe/Athens", country: "GR" },
  { city: "Thessaloniki", tz: "Europe/Athens", country: "GR" },
  { city: "Zagreb", tz: "Europe/Zagreb", country: "HR" },
  { city: "Belgrade", tz: "Europe/Belgrade", country: "RS" },
  { city: "Sarajevo", tz: "Europe/Sarajevo", country: "BA" },
  { city: "Podgorica", tz: "Europe/Podgorica", country: "ME" },
  { city: "Skopje", tz: "Europe/Skopje", country: "MK" },
  { city: "Tirana", tz: "Europe/Tirane", country: "AL" },

  // Europe — Nordic
  { city: "Stockholm", tz: "Europe/Stockholm", country: "SE" },
  { city: "Copenhagen", tz: "Europe/Copenhagen", country: "DK" },
  { city: "Oslo", tz: "Europe/Oslo", country: "NO" },
  { city: "Helsinki", tz: "Europe/Helsinki", country: "FI" },
  { city: "Reykjavik", tz: "Atlantic/Reykjavik", country: "IS" },

  // Europe — Baltic
  { city: "Tallinn", tz: "Europe/Tallinn", country: "EE" },
  { city: "Riga", tz: "Europe/Riga", country: "LV" },
  { city: "Vilnius", tz: "Europe/Vilnius", country: "LT" },

  // Europe — Eastern
  { city: "Moscow", tz: "Europe/Moscow", country: "RU" },
  { city: "St Petersburg", tz: "Europe/Moscow", country: "RU" },
  { city: "Kyiv", tz: "Europe/Kyiv", country: "UA" },
  { city: "Bucharest", tz: "Europe/Bucharest", country: "RO" },
  { city: "Sofia", tz: "Europe/Sofia", country: "BG" },
  { city: "Chisinau", tz: "Europe/Chisinau", country: "MD" },
  { city: "Minsk", tz: "Europe/Minsk", country: "BY" },

  // Europe — Other
  { city: "Istanbul", tz: "Europe/Istanbul", country: "TR" },
  { city: "Ankara", tz: "Europe/Istanbul", country: "TR" },
  { city: "Nicosia", tz: "Asia/Nicosia", country: "CY" },
  { city: "Valletta", tz: "Europe/Malta", country: "MT" },
  { city: "Monaco", tz: "Europe/Monaco", country: "MC" },
  { city: "Andorra la Vella", tz: "Europe/Andorra", country: "AD" },

  // Asia — Middle East
  { city: "Dubai", tz: "Asia/Dubai", country: "AE" },
  { city: "Abu Dhabi", tz: "Asia/Dubai", country: "AE" },
  { city: "Riyadh", tz: "Asia/Riyadh", country: "SA" },
  { city: "Jeddah", tz: "Asia/Riyadh", country: "SA" },
  { city: "Doha", tz: "Asia/Qatar", country: "QA" },
  { city: "Kuwait City", tz: "Asia/Kuwait", country: "KW" },
  { city: "Manama", tz: "Asia/Bahrain", country: "BH" },
  { city: "Muscat", tz: "Asia/Muscat", country: "OM" },
  { city: "Tehran", tz: "Asia/Tehran", country: "IR" },
  { city: "Baghdad", tz: "Asia/Baghdad", country: "IQ" },
  { city: "Amman", tz: "Asia/Amman", country: "JO" },
  { city: "Beirut", tz: "Asia/Beirut", country: "LB" },
  { city: "Damascus", tz: "Asia/Damascus", country: "SY" },
  { city: "Jerusalem", tz: "Asia/Jerusalem", country: "IL" },
  { city: "Tel Aviv", tz: "Asia/Jerusalem", country: "IL" },

  // Asia — Central
  { city: "Almaty", tz: "Asia/Almaty", country: "KZ" },
  { city: "Nur-Sultan", tz: "Asia/Almaty", country: "KZ" },
  { city: "Tashkent", tz: "Asia/Tashkent", country: "UZ" },
  { city: "Bishkek", tz: "Asia/Bishkek", country: "KG" },
  { city: "Dushanbe", tz: "Asia/Dushanbe", country: "TJ" },
  { city: "Ashgabat", tz: "Asia/Ashgabat", country: "TM" },
  { city: "Kabul", tz: "Asia/Kabul", country: "AF" },
  { city: "Baku", tz: "Asia/Baku", country: "AZ" },
  { city: "Tbilisi", tz: "Asia/Tbilisi", country: "GE" },
  { city: "Yerevan", tz: "Asia/Yerevan", country: "AM" },

  // Asia — South
  { city: "Mumbai", tz: "Asia/Kolkata", country: "IN" },
  { city: "Delhi", tz: "Asia/Kolkata", country: "IN" },
  { city: "New Delhi", tz: "Asia/Kolkata", country: "IN" },
  { city: "Bangalore", tz: "Asia/Kolkata", country: "IN" },
  { city: "Chennai", tz: "Asia/Kolkata", country: "IN" },
  { city: "Hyderabad", tz: "Asia/Kolkata", country: "IN" },
  { city: "Kolkata", tz: "Asia/Kolkata", country: "IN" },
  { city: "Pune", tz: "Asia/Kolkata", country: "IN" },
  { city: "Ahmedabad", tz: "Asia/Kolkata", country: "IN" },
  { city: "Islamabad", tz: "Asia/Karachi", country: "PK" },
  { city: "Karachi", tz: "Asia/Karachi", country: "PK" },
  { city: "Lahore", tz: "Asia/Karachi", country: "PK" },
  { city: "Dhaka", tz: "Asia/Dhaka", country: "BD" },
  { city: "Colombo", tz: "Asia/Colombo", country: "LK" },
  { city: "Kathmandu", tz: "Asia/Kathmandu", country: "NP" },
  { city: "Thimphu", tz: "Asia/Thimphu", country: "BT" },
  { city: "Male", tz: "Indian/Maldives", country: "MV" },

  // Asia — Southeast
  { city: "Singapore", tz: "Asia/Singapore", country: "SG" },
  { city: "Bangkok", tz: "Asia/Bangkok", country: "TH" },
  { city: "Jakarta", tz: "Asia/Jakarta", country: "ID" },
  { city: "Bali", tz: "Asia/Makassar", country: "ID" },
  { city: "Kuala Lumpur", tz: "Asia/Kuala_Lumpur", country: "MY" },
  { city: "Manila", tz: "Asia/Manila", country: "PH" },
  { city: "Ho Chi Minh City", tz: "Asia/Ho_Chi_Minh", country: "VN" },
  { city: "Hanoi", tz: "Asia/Ho_Chi_Minh", country: "VN" },
  { city: "Phnom Penh", tz: "Asia/Phnom_Penh", country: "KH" },
  { city: "Vientiane", tz: "Asia/Vientiane", country: "LA" },
  { city: "Yangon", tz: "Asia/Yangon", country: "MM" },
  { city: "Brunei", tz: "Asia/Brunei", country: "BN" },
  { city: "Dili", tz: "Asia/Dili", country: "TL" },

  // Asia — East
  { city: "Tokyo", tz: "Asia/Tokyo", country: "JP" },
  { city: "Osaka", tz: "Asia/Tokyo", country: "JP" },
  { city: "Kyoto", tz: "Asia/Tokyo", country: "JP" },
  { city: "Seoul", tz: "Asia/Seoul", country: "KR" },
  { city: "Busan", tz: "Asia/Seoul", country: "KR" },
  { city: "Beijing", tz: "Asia/Shanghai", country: "CN" },
  { city: "Shanghai", tz: "Asia/Shanghai", country: "CN" },
  { city: "Shenzhen", tz: "Asia/Shanghai", country: "CN" },
  { city: "Guangzhou", tz: "Asia/Shanghai", country: "CN" },
  { city: "Chengdu", tz: "Asia/Shanghai", country: "CN" },
  { city: "Hong Kong", tz: "Asia/Hong_Kong", country: "HK" },
  { city: "Macau", tz: "Asia/Macau", country: "MO" },
  { city: "Taipei", tz: "Asia/Taipei", country: "TW" },
  { city: "Ulaanbaatar", tz: "Asia/Ulaanbaatar", country: "MN" },
  { city: "Pyongyang", tz: "Asia/Pyongyang", country: "KP" },

  // Asia — Russia (Asian part)
  { city: "Vladivostok", tz: "Asia/Vladivostok", country: "RU" },
  { city: "Novosibirsk", tz: "Asia/Novosibirsk", country: "RU" },
  { city: "Yekaterinburg", tz: "Asia/Yekaterinburg", country: "RU" },
  { city: "Krasnoyarsk", tz: "Asia/Krasnoyarsk", country: "RU" },
  { city: "Irkutsk", tz: "Asia/Irkutsk", country: "RU" },
  { city: "Yakutsk", tz: "Asia/Yakutsk", country: "RU" },
  { city: "Magadan", tz: "Asia/Magadan", country: "RU" },
  { city: "Kamchatka", tz: "Asia/Kamchatka", country: "RU" },
  { city: "Sakhalin", tz: "Asia/Sakhalin", country: "RU" },

  // Africa — North
  { city: "Cairo", tz: "Africa/Cairo", country: "EG" },
  { city: "Alexandria", tz: "Africa/Cairo", country: "EG" },
  { city: "Casablanca", tz: "Africa/Casablanca", country: "MA" },
  { city: "Rabat", tz: "Africa/Casablanca", country: "MA" },
  { city: "Tunis", tz: "Africa/Tunis", country: "TN" },
  { city: "Algiers", tz: "Africa/Algiers", country: "DZ" },
  { city: "Tripoli", tz: "Africa/Tripoli", country: "LY" },
  { city: "Khartoum", tz: "Africa/Khartoum", country: "SD" },

  // Africa — West
  { city: "Lagos", tz: "Africa/Lagos", country: "NG" },
  { city: "Abuja", tz: "Africa/Lagos", country: "NG" },
  { city: "Accra", tz: "Africa/Accra", country: "GH" },
  { city: "Dakar", tz: "Africa/Dakar", country: "SN" },
  { city: "Abidjan", tz: "Africa/Abidjan", country: "CI" },
  { city: "Bamako", tz: "Africa/Bamako", country: "ML" },
  { city: "Ouagadougou", tz: "Africa/Ouagadougou", country: "BF" },
  { city: "Conakry", tz: "Africa/Conakry", country: "GN" },
  { city: "Freetown", tz: "Africa/Freetown", country: "SL" },
  { city: "Monrovia", tz: "Africa/Monrovia", country: "LR" },
  { city: "Lome", tz: "Africa/Lome", country: "TG" },
  { city: "Cotonou", tz: "Africa/Porto-Novo", country: "BJ" },
  { city: "Niamey", tz: "Africa/Niamey", country: "NE" },
  { city: "Nouakchott", tz: "Africa/Nouakchott", country: "MR" },

  // Africa — East
  { city: "Nairobi", tz: "Africa/Nairobi", country: "KE" },
  { city: "Addis Ababa", tz: "Africa/Addis_Ababa", country: "ET" },
  { city: "Dar es Salaam", tz: "Africa/Dar_es_Salaam", country: "TZ" },
  { city: "Kampala", tz: "Africa/Kampala", country: "UG" },
  { city: "Mogadishu", tz: "Africa/Mogadishu", country: "SO" },
  { city: "Asmara", tz: "Africa/Asmara", country: "ER" },
  { city: "Djibouti", tz: "Africa/Djibouti", country: "DJ" },
  { city: "Antananarivo", tz: "Indian/Antananarivo", country: "MG" },
  { city: "Port Louis", tz: "Indian/Mauritius", country: "MU" },

  // Africa — Central
  { city: "Kinshasa", tz: "Africa/Kinshasa", country: "CD" },
  { city: "Lubumbashi", tz: "Africa/Lubumbashi", country: "CD" },
  { city: "Brazzaville", tz: "Africa/Brazzaville", country: "CG" },
  { city: "Douala", tz: "Africa/Douala", country: "CM" },
  { city: "Yaounde", tz: "Africa/Douala", country: "CM" },
  { city: "Libreville", tz: "Africa/Libreville", country: "GA" },
  { city: "Bangui", tz: "Africa/Bangui", country: "CF" },
  { city: "Ndjamena", tz: "Africa/Ndjamena", country: "TD" },
  { city: "Luanda", tz: "Africa/Luanda", country: "AO" },

  // Africa — Southern
  { city: "Johannesburg", tz: "Africa/Johannesburg", country: "ZA" },
  { city: "Cape Town", tz: "Africa/Johannesburg", country: "ZA" },
  { city: "Pretoria", tz: "Africa/Johannesburg", country: "ZA" },
  { city: "Durban", tz: "Africa/Johannesburg", country: "ZA" },
  { city: "Harare", tz: "Africa/Harare", country: "ZW" },
  { city: "Lusaka", tz: "Africa/Lusaka", country: "ZM" },
  { city: "Maputo", tz: "Africa/Maputo", country: "MZ" },
  { city: "Lilongwe", tz: "Africa/Blantyre", country: "MW" },
  { city: "Gaborone", tz: "Africa/Gaborone", country: "BW" },
  { city: "Windhoek", tz: "Africa/Windhoek", country: "NA" },
  { city: "Kigali", tz: "Africa/Kigali", country: "RW" },
  { city: "Bujumbura", tz: "Africa/Bujumbura", country: "BI" },

  // Oceania — Australia
  { city: "Sydney", tz: "Australia/Sydney", country: "AU" },
  { city: "Melbourne", tz: "Australia/Melbourne", country: "AU" },
  { city: "Brisbane", tz: "Australia/Brisbane", country: "AU" },
  { city: "Perth", tz: "Australia/Perth", country: "AU" },
  { city: "Adelaide", tz: "Australia/Adelaide", country: "AU" },
  { city: "Canberra", tz: "Australia/Sydney", country: "AU" },
  { city: "Hobart", tz: "Australia/Hobart", country: "AU" },
  { city: "Darwin", tz: "Australia/Darwin", country: "AU" },

  // Oceania — New Zealand & Pacific
  { city: "Auckland", tz: "Pacific/Auckland", country: "NZ" },
  { city: "Wellington", tz: "Pacific/Auckland", country: "NZ" },
  { city: "Christchurch", tz: "Pacific/Auckland", country: "NZ" },
  { city: "Fiji", tz: "Pacific/Fiji", country: "FJ" },
  { city: "Suva", tz: "Pacific/Fiji", country: "FJ" },
  { city: "Port Moresby", tz: "Pacific/Port_Moresby", country: "PG" },
  { city: "Noumea", tz: "Pacific/Noumea", country: "NC" },
  { city: "Apia", tz: "Pacific/Apia", country: "WS" },
  { city: "Nuku'alofa", tz: "Pacific/Tongatapu", country: "TO" },
  { city: "Pago Pago", tz: "Pacific/Pago_Pago", country: "AS" },
  { city: "Guam", tz: "Pacific/Guam", country: "GU" },
  { city: "Tahiti", tz: "Pacific/Tahiti", country: "PF" },

  // Atlantic
  { city: "Reykjavik", tz: "Atlantic/Reykjavik", country: "IS" },
  { city: "Azores", tz: "Atlantic/Azores", country: "PT" },
  { city: "Cape Verde", tz: "Atlantic/Cape_Verde", country: "CV" },
  { city: "Bermuda", tz: "Atlantic/Bermuda", country: "BM" },

  // Indian Ocean
  { city: "Reunion", tz: "Indian/Reunion", country: "RE" },
  { city: "Seychelles", tz: "Indian/Mahe", country: "SC" },
];
